# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Build debug APK and distribute to Firebase testers"
  lane :firebase_debug do
    gradle(
      task: "assemble",
      build_type: "Debug",
      project_dir: "."
    )
    firebase_app_distribution(
      app: "1:798096595312:android:c2c877b5b2bf68f81c97b5", 
      android_artifact_path: "app/build/outputs/apk/debug/app-debug.apk",
      release_notes: "Latest Android debug build",
      testers: "fikritestings@gmail.com",  
      groups: "testing-ajah"
    )
  end

  desc "Build release APK and distribute"
  lane :firebase_release do
    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "."
    )
        firebase_app_distribution(
          app: "1:798096595312:android:c2c877b5b2bf68f81c97b5",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      release_notes: `git log -1 --pretty=%B`,
      groups: "testing-ajah"
    )
  end
end
